language: csharp
solution: FlipperDotNet.sln
script:
  - xbuild /p:Configuration=Release FlipperDotNet.sln
  - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./FlipperDotNet.Tests/bin/Release/FlipperDotNet.Tests.dll
