language: csharp
solution: FlipperDotNet.sln
script:
  - xbuild /p:Configuration=Release FlipperDotNet.sln
  - find / -name *nunit*
  - nunit-console ./FlipperDotNet.Tests/bin/Release/FlipperDotNet.Tests.dll
