language: csharp
solution: FlipperDotNet.sln
before_install:
    - ./build_redis.sh
    - ./install_consul.sh
script:
    - xbuild /p:Configuration=Release FlipperDotNet.sln
    - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./FlipperDotNet.ConsulAdapter.Tests/bin/Release/FlipperDotNet.ConsulAdapter.Tests.dll
    - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./FlipperDotNet.ConsulAdapter.Tests.Interop/bin/Release/FlipperDotNet.ConsulAdapter.Tests.Interop.dll
addons:
  apt:
    packages:
      - unzip