language: csharp
solution: FlipperDotNet.sln
before_install:
    - ./build_redis.sh
script:
    - xbuild /p:Configuration=Release FlipperDotNet.sln
    - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./FlipperDotNet.RedisAdapter.Tests/bin/Release/FlipperDotNet.RedisAdapter.Tests.dll
