language: csharp
solution: FlipperDotNet.sln
before_install:
    - ./build_redis.sh
    - curl -sS http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip > /tmp/pcl-assemblies.zip
    - unzip /tmp/pcl-assemblies.zip -d /tmp/pcl-assemblies && mv /tmp/pcl-assemblies/PortableReferenceAssemblies-2014-04-14 /tmp/pcl-assemblies/.NETPortable
    - export XBUILD_FRAMEWORK_FOLDERS_PATH=/tmp/pcl-assemblies/
script:
    - xbuild /p:Configuration=Release FlipperDotNet.sln
    - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./FlipperDotNet.Tests/bin/Release/FlipperDotNet.Tests.dll
